[tool.poetry]
name = "numbat-tasks-api"
version = "0.1.0"
description = "Backend API for Numbat Tasks"
authors = ["Michael Van Delft <michael@hybr.id.au>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
djangorestframework = "^3.14.0"
python-decouple = "^3.8"
psycopg = {extras = ["binary"], version = "^3.1.17"}
drf-spectacular = {extras = ["sidecar"], version = "^0.27.1"}

[tool.poetry.group.dev.dependencies]
black = "^23.12.1"
isort = "^5.13.2"
flake8 = "^7.0.0"
ipython = "^8.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
