name: Frontend TypeScript Linting
on: [pull_request]
defaults:
    working-directory: ./frontend
jobs:
    lint-typescript-files:
        runs-on: ubuntu-latest
        steps:
            # Setup
            - name: Check out repository code
              uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'npm'
            - run: pnpm install
            - name: TypeScript Check
              run: pnpm tsc
            - name: Biome check
              run: pnpm biome check src

