name: Python Linting
on: [pull_request]
jobs:
    lint-python-files:
        runs-on: ubuntu-latest
        steps:
            # Setup
            - name: Check out repository code
              uses: actions/checkout@v4
            - run: cd api
            - run: pip install poetry
            - run: poetry install --only linting

            # Tests
            - name: black
              run: black --check .

            - name: isort
              run: isort --check .

            - name: flake8
              run: flake8 .
